### ISSUE TITLE
Assess Sensophone Alarm system

### ISSUE THREAD

**Issue by sr320** [RobertsLab/2017-hackweek#1]

**Comment by kubu4** [comment]
Assessed.

Fixed Alarm 3 (Revco - Horner-Devine Lab freezer) to trigger correctly (wires were wired incorrectly causing alarm status to trigger once freezer returned to normal operating temperature range - instead of triggering when freezer temps were outside of normal operating range).

Updated/corrected/improved Sensaphone documentation in [LabDocs Wiki](https://github.com/sr320/LabDocs/wiki/Alarm-Information).

**Comment by kubu4** [comment]
Revco freezer seems to be solely contain Young Lab stuff. Should we add them to Sensaphone call list or should we remove Revco from our Sensaphone and let them deal with monitoring that freezer?

**Comment by kubu4** [comment]
Revco should be considered as a backup freezer - not full time use for Young Lab (or Roberts Lab).
